version: '3.8'
services:
  app:
    build: .
    ports:
      - "8090:8090"
    environment:
      SPRING_DATA_MONGODB_URI: mongodb://mongo:27017/geolocation
    depends_on:
      - mongo

  mongo:
    image: mongo:latest
    container_name: geolocation-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data: