#Service Identification
name:
  component: bac-ml-ms-geolocation-ip-java
id:
  service: bac-ml-ms-geolocation-ip-java


#Params of Execution
server:
  port: ${PORT:8090}
spring:
  webflux:
    base-path: /mercadolibre/geolocation/ip
  thymeleaf:
    mode: HTML
    cache: false
    prefix: classpath:/templates/
    suffix: .html
  application:
  name: bac-ml-ms-geolocation-ip-java
  data:
    mongodb:
      uri: ${SPRING_DATA_MONGODB_URI}

#External API
services:
  consult-country:
    host: https://restcountries.com
    url: /v3.1/name/
  consult-ip:
    host: http://ip-api.com
    url: /json/
  consult-currency:
    host: https://v6.exchangerate-api.com
    api-key: 580b532bd065fbbc41f98e13
    url: /v6/${services.consult-currency.api-key}/latest/
  cache:
    time: 10
  timeout: 5000

#Cache Logger
logging:
  level:
    org:
      springframework:
        cache: TRACE

#Swagger
springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method
  model-converters:
    enabled: true